;Core
ze_core.amxx

;Setting API / Models
amx_settings_api.amxx
cs_weap_models_api.amxx

;Mod Addons
ze_block_events_messages.amxx
ze_effects_messages.amxx
ze_nightvision_lighting.amxx
ze_effects_frags.amxx
ze_effects_weather.amxx
ze_coins_system.amxx
ze_hud_info.amxx
ze_weapon_menu.amxx
ze_main_menu.amxx
ze_items_manager.amxx
ze_items_escape_coins.amxx
ze_items_limit.amxx
ze_fire.amxx
ze_frost.amxx
ze_resources.amxx
ze_countdown.amxx
ze_zombie_sounds.amxx

;Enable if needed
;ze_items_level.amxx	;Level System needed.
;ze_items_vip.amxx		;VIP System needed.

;Gameplay Addons
ze_target_info.amxx
ze_breakable_hint.amxx
ze_win_message.amxx
ze_multijump.amxx
ze_firenade_effects.amxx
ze_frostnade_effects.amxx
ze_ice_cube.amxx
ze_reset_score.amxx
ze_block_tank_guns.amxx
ze_coins_change.amxx
ze_CustomFlashLight.amxx
parachute.amxx
nademodes.amxx
bullet_damage.amxx
advanced_weapon_tracers.amxx
ze_show_zombie_hp.amxx
ad_manager.amxx
GHW_Weapon_Replacement.amxx
escape_progress_bar.amxx
no_recoil.amxx
no_clip.amxx
played_time.amxx
block_damage.amxx

;Extra-Items
ze_extra_fire_nade.amxx
ze_extra_frost_nade.amxx
ze_madness.amxx
force_shield_grenade.amxx
ze_extra_weapon_ammo.amxx
ze_extra_unlimited_clip.amxx
ze_frost_m4a1.amxx
ze_stun_rifle.amxx