gfx/env/ko_hellwaybk.tga
gfx/env/ko_hellwaydn.tga
gfx/env/ko_hellwayft.tga
gfx/env/ko_hellwaylf.tga
gfx/env/ko_hellwayrt.tga
gfx/env/ko_hellwayup.tga
models/KO/earth.mdl
models/KO/ko_door1.mdl
models/KO/ko_eletric1.mdl
models/KO/ko_fence2.mdl
models/KO/ko_gaspipes.mdl
models/KO/ko_grating2.mdl
models/KO/ko_grating3.mdl
models/KO/ko_halo01.mdl
models/KO/ko_light2.mdl
models/KO/ko_light3.mdl
models/KO/ko_pipe2.mdl
models/KO/ko_pipes5.mdl
models/KO/ko_pipes6.mdl
models/KO/ko_pipes7.mdl
models/KO/ko_reactor.mdl
models/KO/ko_reactor2.mdl
models/KO/ko_sky_sphere1.mdl
models/KO/ko_storage_closet.mdl
models/KO/ko_tank1.mdl
models/KO/ko_tower2.mdl
models/KO/ko_trash1.mdl
models/KO/ko_tube1.mdl
models/KO/ko_vent1.mdl
models/KO/pad_twist.mdl
models/KO/stargate.mdl
models/KO/stargate2.mdl
models/KO/twist.mdl

sound/KO/0001.wav

sprites/KO/ko_fire1.spr
sprites/ko/ko_flux.spr
sprites/KO/KO_glow01.spr
sprites/ko/ko_smoke5.spr
sprites/ko/ko_smoke6.spr
sprites/KO/lgtning.spr
sprites/ko/light.spr
sprites/ko/xbeam1.spr
sprites/KO/yelflare1.spr

