gfx/env/dustbk.tga
gfx/env/dustdn.tga
gfx/env/dustft.tga
gfx/env/dustlf.tga
gfx/env/dustrt.tga
gfx/env/dustup.tga
models/props/cs_office/swat_van.mdl
models/props/de_nuke/nuke_modelgroup_static.mdl
models/props/de_nuke/nuke_modelgroup_static2.mdl
sound/ambience/truck2.wav
sound/csg/ac_loop.wav
sound/csg/bsite_ambient.wav
sound/csg/catwalk_sound.wav
sound/csg/crashed_truck.wav
sound/csg/door_open.wav
sound/csg/loadingroom_ambient.wav
sound/csg/nuke_ambient.wav
sound/csg/pipe_ins_sound.wav
sound/csg/pipeleak_sound.wav
sound/csg/tank_ins.wav
sound/csg/transformer_sound.wav
sprites/2dprops/reflection.spr
sprites/particles/Glow.spr