// de_mirage.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (90):
cs_dust.wad
czde_dust.wad
czde_prodigy.wad
de_dust0.wad
de_mirage.wad
de_piranesi.wad
de_rats.wad
de_turkey.wad
decals.wad
gfx/env/hs_bk.tga
gfx/env/hs_dn.tga
gfx/env/hs_ft.tga
gfx/env/hs_lf.tga
gfx/env/hs_rt.tga
gfx/env/hs_up.tga
grid_cso.wad
models/bg_light04.mdl
models/bg_light06.mdl
models/bg_meat.mdl
models/brokenwall01.mdl
models/bzm_metro/metro_elec_box.mdl
models/bzm_metro/metro_elec_switch.mdl
models/cart01.mdl
models/de_mirage/antenna.mdl
models/de_mirage/bg_sopa01.mdl
models/de_mirage/bg_weaponbox01.mdl
models/de_mirage/bg_weaponbox02.mdl
models/de_mirage/bg_weaponbox03.mdl
models/de_mirage/cart01_small.mdl
models/de_mirage/chimney_metalic.mdl
models/de_mirage/desert_lamp.mdl
models/de_mirage/whabun03.mdl
models/desert_an01.mdl
models/fan_ceiling.mdl
models/gibs_stairsmetal.mdl
models/hay02.mdl
models/longchair01.mdl
models/med_crategibs.mdl
models/mil_crategibs.mdl
models/palmtree02.mdl
models/pi_fern.mdl
models/pi_shrub.mdl
models/pole_har.mdl
models/pred_plant.mdl
models/props/apc_gray.mdl
models/props/bg_light_r03.mdl
models/props/trash.mdl
models/props/trash_02.mdl
models/props/trash_04.mdl
models/props/trash_05.mdl
models/props/trash_trashbag.mdl
models/pve_standalone/bg_beverage_set.mdl
models/pve_standalone/bg_garbage01.mdl
models/pve_standalone_obj/bicycle_dead.mdl
models/pve_standalone_obj/can_acetone-pair.mdl
models/pve_standalone_obj/cans_paint-old.mdl
models/pve_standalone_obj/cashregister_damaged.mdl
models/pve_standalone_obj/coffee_maker.mdl
models/pve_standalone_obj/geo_motor.mdl
models/pve_standalone_obj/lamp_portable_standup.mdl
models/pve_standalone_obj/oxygen_tanks.mdl
models/pve_standalone_obj/paper_cup.mdl
models/pve_standalone_obj/shelves_warehouse.mdl
models/pve_standalone_obj/weldtank.mdl
models/shelter/zb_dish.mdl
models/shelter/zb_drinks.mdl
models/shovel02.mdl
models/whabun01.mdl
models/whabun02.mdl
models/ze_venice/bg_light03.mdl
models/ze_venice/bicycle.mdl
models/zm_darkcity/bg_pole02.mdl
models/zm_darkcity/bg_trash_bin.mdl
models/zm_darkcity/bg_trashcan.mdl
models/zm_darkcity/bg_trashcan_set.mdl
models/zm_darkcity/car_vanB01.mdl
models/zs_conspiracy/cons_yellowpipe_04_1.mdl
models/zs_conspiracy/cons_yellowpipe_05.mdl
models/zs_evacuate/mattress02.mdl
models/zs_evacuate/oldchair01.mdl
models/zs_evacuate/oldshelf01.mdl
models/zs_memories/bg_autobai01_duty.mdl
models/zsh_deadcity/zb_tool_01.mdl
pve_standalone1.wad
pve_standalone2.wad
pve_standalone3.wad
sound/ambience/silo_wind_loop.wav
sound/ambience/wind_camo.wav
sound/ambience/wind_litegust.wav
sprites/3dmflagld.spr
