gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
maps/dm_shipment.bsp
maps/dm_shipment.res
models/props/barrel_blue.mdl
models/props/barrel_brown.mdl
models/props/barrel_orange.mdl
models/props/barrels_pallet.mdl
models/props/buzzer_podstavka0.mdl
models/props/car_lada.mdl
models/props/crane.mdl
models/props/crates_still.mdl
models/props/dumpster_lidclosed.mdl
models/props/grass.mdl
models/props/jeb.mdl
models/props/jeep-russian.mdl
models/props/pallet_stack.mdl
models/props/rusted_car.mdl
models/props/stepvan2.mdl
models/props/street.mdl
models/props/trash3.mdl
models/props/trash_02.mdl
models/props/tree_pine_big.mdl
models/props/tree_pine_mid.mdl
models/props/truck_large-green.mdl
models/props/water_tower_big.mdl
models/props/zp_junk01.mdl
models/props/zp_junk02.mdl
models/props/zp_trash.mdl.mdl
sound/ambience/assaultloop2.wav
