# Description
#
# semiclip 0 | 1 Disable / Enable semiclip
# team 0 | 1 | 2 | 3
# - 0 Semiclip is valid for all
# - 1 Semiclip only valid for T
# - 2 Semiclip only valid for CT
# - 3 Semiclip only works for teammates
#
# time 0 | 180 How long is the semiclip action from the beginning of the round?
# crouch 0 | 1 Automation of replanting.
# effects 0 | 1 The transparency effect of the player depends on the distance between the players.
# distance 64 | 250 At which distance a player can have transparency and a semiclip action.
# transparency 0 | 255 Transparency of the player.
# penetfire 0 | 1 Pass fire on the "transparent" allies.
#

semiclip = 1;
team = 2;
time = 0;
crouch = 1;
effects = 1;
distance = 200;
transparency = 100;
penetfire = 0;